version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./cache:/app/cache
    environment:
      - DATABASE_URL=sqlite:///./option_pricing.db
      - LOG_LEVEL=INFO
      - USE_GPU=false
    command: python -m uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./cache:/app/cache
    environment:
      - DATABASE_URL=sqlite:///./option_pricing.db
      - LOG_LEVEL=INFO
      - USE_GPU=false
      - PYTHONPATH=/app
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    env_file:
      - .env
    command: streamlit run web/app.py --server.port 8501 --server.address 0.0.0.0

  tests:
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./option_pricing.db
      - LOG_LEVEL=INFO
      - USE_GPU=false
    command: pytest tests/

  docs:
    build: .
    volumes:
      - .:/app
    command: sh -c "cd docs && make html"
