from setuptools import setup, find_packages

setup(
    name="mpc_option_pricing",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "mpyc>=0.8.0",
        "matplotlib>=3.4.0",
        "pandas>=1.3.0",
        "yfinance>=0.2.36",
        "seaborn>=0.12.0",
        "plotly>=5.18.0",
        "streamlit>=1.22.0",
        "fastapi>=0.95.0",
        "uvicorn>=0.22.0",
        "pytest>=7.3.1",
        "pytest-cov>=4.1.0",
        "sphinx>=6.1.3",
        "sphinx-rtd-theme>=1.2.0",
        "python-dotenv>=1.0.0",
        "sqlalchemy>=2.0.15",
        "psycopg2-binary>=2.9.6",
        "pydantic>=2.0.2",
        "loguru>=0.7.0",
    ],
    extras_require={
        "dev": [
            "pytest",
            "pytest-cov",
            "black",
            "isort",
            "flake8",
            "mypy",
            "pre-commit",
        ],
        "gpu": [
            "cupy-cuda11x",
            "numba",
        ],
    },
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="A comprehensive MPC-based option pricing system with multiple models and features",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/mpc_option_pricing",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
) 